/// @desc The bullet catalogue -- GENERATED by tools/make_bullets.py. Do not
///       edit: each hit radius is defined there beside its picture. A shape
///       is one sprite whose frames are its colours; `bullet_frame` computes
///       the frame index.


#macro BSHAPE_PELLET 0
#macro BSHAPE_ORB 1
#macro BSHAPE_BALL 2
#macro BSHAPE_SPHERE 3
#macro BSHAPE_RING 4
#macro BSHAPE_BUBBLE 5
#macro BSHAPE_RICE 6
#macro BSHAPE_DROPLET 7
#macro BSHAPE_OVAL 8
#macro BSHAPE_DART 9
#macro BSHAPE_KNIFE 10
#macro BSHAPE_ARROW 11
#macro BSHAPE_CARD 12
#macro BSHAPE_STAR 13
#macro BSHAPE_SHURIKEN 14
#macro BSHAPE_CRYSTAL 15
#macro BSHAPE_RUNE 16
#macro BSHAPE_BUTTERFLY 17
#macro BSHAPE_FLAME 18
#macro BSHAPE_MOTE 19
#macro BSHAPE_NOVA 20
#macro BSHAPE_COUNT 21

#macro BCOL_CRIMSON 0
#macro BCOL_EMBER 1
#macro BCOL_AMBER 2
#macro BCOL_GOLD 3
#macro BCOL_LIME 4
#macro BCOL_JADE 5
#macro BCOL_SPRING 6
#macro BCOL_CYAN 7
#macro BCOL_AZURE 8
#macro BCOL_INDIGO 9
#macro BCOL_VIOLET 10
#macro BCOL_MAGENTA 11
#macro BCOL_ROSE 12
#macro BCOL_BONE 13
#macro BCOL_COUNT 14

#macro BRAY_BODY0 1.00
#macro BRAY_BODY1 127.00
#macro BRAY_THICK 32.00
#macro BRAY_TAPER 26.00

/// @desc Fill in the shape table. Called once, from obj_boot.
function bullet_table_init() {
    global.bshape_sprite = [
        spr_bul_pellet,
        spr_bul_orb,
        spr_bul_ball,
        spr_bul_sphere,
        spr_bul_ring,
        spr_bul_bubble,
        spr_bul_rice,
        spr_bul_droplet,
        spr_bul_oval,
        spr_bul_dart,
        spr_bul_knife,
        spr_bul_arrow,
        spr_bul_card,
        spr_bul_star,
        spr_bul_shuriken,
        spr_bul_crystal,
        spr_bul_rune,
        spr_bul_butterfly,
        spr_bul_flame,
        spr_bul_mote,
        spr_bul_nova,
    ];
    global.bshape_radius = [
        3.3, 7.0, 15.0, 20.5, 18.5, 42.0, 3.7, 6.0, 7.8, 2.9, 2.4, 1.5, 8.5, 10.5, 9.0, 6.4, 8.0, 14.0, 9.5, 4.3, 9.0,
    ];
    global.bshape_oriented = [
        false, false, false, false, false, false, true, true, true, true, true, true, true, false, false, true, false, true, true, false, false,
    ];
    global.bshape_frames = [
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4,
    ];
    global.bshape_w = [
        34, 48, 68, 76, 80, 138, 48, 50, 52, 60, 68, 72, 60, 56, 56, 58, 44, 92, 80, 42, 84,
    ];
    global.bshape_h = [
        34, 48, 68, 76, 80, 138, 36, 38, 36, 44, 34, 32, 44, 56, 56, 46, 44, 78, 56, 42, 84,
    ];
    global.bshape_spin = [
        0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 2.20, 9.00, 0.00, 0.00, 0.00, 0.00, 2.80, 2.80,
    ];
    global.bshape_long = [
        false, false, false, false, false, false, true, false, true, true, true, true, true, false, false, true, false, false, false, false, false,
    ];
    global.bshape_spine0 = [
        0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -9.50, 0.00, -7.75, -16.50, -23.25, -47.50, -5.25, 0.00, 0.00, -11.25, 0.00, 0.00, 0.00, 0.00, 0.00,
    ];
    global.bshape_spine1 = [
        0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 9.75, 0.00, 7.75, 15.50, 18.75, 4.00, 9.75, 0.00, 0.00, 11.50, 0.00, 0.00, 0.00, 0.00, 0.00,
    ];
    global.bshape_ext = [
        0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 9.75, 0.00, 7.75, 16.50, 23.25, 47.50, 9.75, 0.00, 0.00, 11.50, 0.00, 0.00, 0.00, 0.00, 0.00,
    ];
}

