/// @desc The bullet catalogue -- GENERATED by tools/make_bullets.py. Do not
///       edit: each hit radius is defined there beside its picture. A shape
///       is one sprite whose frames are its colours; `bullet_frame` computes
///       the frame index.


#macro BSHAPE_PELLET 0
#macro BSHAPE_ORB 1
#macro BSHAPE_BALL 2
#macro BSHAPE_SPHERE 3
#macro BSHAPE_RING 4
#macro BSHAPE_BUBBLE 5
#macro BSHAPE_RICE 6
#macro BSHAPE_DROPLET 7
#macro BSHAPE_OVAL 8
#macro BSHAPE_DART 9
#macro BSHAPE_KNIFE 10
#macro BSHAPE_ARROW 11
#macro BSHAPE_CARD 12
#macro BSHAPE_STAR 13
#macro BSHAPE_SHURIKEN 14
#macro BSHAPE_CRYSTAL 15
#macro BSHAPE_RUNE 16
#macro BSHAPE_BUTTERFLY 17
#macro BSHAPE_FLAME 18
#macro BSHAPE_MOTE 19
#macro BSHAPE_NOVA 20
#macro BSHAPE_COUNT 21

#macro BCOL_CRIMSON 0
#macro BCOL_EMBER 1
#macro BCOL_AMBER 2
#macro BCOL_GOLD 3
#macro BCOL_LIME 4
#macro BCOL_JADE 5
#macro BCOL_SPRING 6
#macro BCOL_CYAN 7
#macro BCOL_AZURE 8
#macro BCOL_INDIGO 9
#macro BCOL_VIOLET 10
#macro BCOL_MAGENTA 11
#macro BCOL_ROSE 12
#macro BCOL_BONE 13
#macro BCOL_COUNT 14

/// @desc Fill in the shape table. Called once, from obj_boot.
function bullet_table_init() {
    global.bshape_sprite = [
        spr_bul_pellet,
        spr_bul_orb,
        spr_bul_ball,
        spr_bul_sphere,
        spr_bul_ring,
        spr_bul_bubble,
        spr_bul_rice,
        spr_bul_droplet,
        spr_bul_oval,
        spr_bul_dart,
        spr_bul_knife,
        spr_bul_arrow,
        spr_bul_card,
        spr_bul_star,
        spr_bul_shuriken,
        spr_bul_crystal,
        spr_bul_rune,
        spr_bul_butterfly,
        spr_bul_flame,
        spr_bul_mote,
        spr_bul_nova,
    ];
    global.bshape_radius = [
        4.2, 7.0, 15.0, 20.5, 12.5, 26.0, 5.6, 6.0, 6.8, 7.6, 6.0, 5.4, 9.0, 10.5, 9.0, 9.0, 8.0, 10.5, 9.5, 5.6, 9.2,
    ];
    global.bshape_oriented = [
        false, false, false, false, false, false, true, true, true, true, true, true, true, false, false, true, false, true, true, false, false,
    ];
    global.bshape_frames = [
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4,
    ];
    global.bshape_w = [
        38, 48, 68, 76, 60, 90, 48, 50, 52, 60, 68, 72, 60, 56, 56, 58, 44, 70, 80, 42, 66,
    ];
    global.bshape_h = [
        38, 48, 68, 76, 60, 90, 36, 37, 36, 44, 34, 31, 44, 56, 56, 46, 44, 60, 56, 42, 66,
    ];
    global.bshape_spin = [
        0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 2.20, 9.00, 0.00, 0.00, 0.00, 0.00, 2.80, 2.80,
    ];
}

