/// @desc The bullet catalogue -- GENERATED by tools/make_bullets.py.
///
/// **Do not edit this file.** A bullet's hit radius and its picture have to
/// agree, and the picture is drawn in Python; a radius maintained by hand here
/// would drift from the sprite it describes within a week. Change
/// `tools/make_bullets.py` and re-run it.
///
/// A shape is one sprite whose frames are its colours. An animated shape folds
/// both axes into the one index, and `bullet_frame` is the only thing allowed
/// to compute it.


#macro BSHAPE_PELLET 0
#macro BSHAPE_ORB 1
#macro BSHAPE_BALL 2
#macro BSHAPE_SPHERE 3
#macro BSHAPE_RING 4
#macro BSHAPE_BUBBLE 5
#macro BSHAPE_RICE 6
#macro BSHAPE_OVAL 7
#macro BSHAPE_DART 8
#macro BSHAPE_NEEDLE 9
#macro BSHAPE_CARD 10
#macro BSHAPE_STAR 11
#macro BSHAPE_STAR6 12
#macro BSHAPE_CRYSTAL 13
#macro BSHAPE_RUNE 14
#macro BSHAPE_BUTTERFLY 15
#macro BSHAPE_FLAME 16
#macro BSHAPE_MOTE 17
#macro BSHAPE_COUNT 18

#macro BCOL_CRIMSON 0
#macro BCOL_EMBER 1
#macro BCOL_AMBER 2
#macro BCOL_GOLD 3
#macro BCOL_LIME 4
#macro BCOL_JADE 5
#macro BCOL_SPRING 6
#macro BCOL_CYAN 7
#macro BCOL_AZURE 8
#macro BCOL_INDIGO 9
#macro BCOL_VIOLET 10
#macro BCOL_MAGENTA 11
#macro BCOL_ROSE 12
#macro BCOL_BONE 13
#macro BCOL_COUNT 14

/// @desc Fill in the shape table. Called once, from obj_boot.
function bullet_table_init() {
    global.bshape_sprite = [
        spr_bul_pellet,
        spr_bul_orb,
        spr_bul_ball,
        spr_bul_sphere,
        spr_bul_ring,
        spr_bul_bubble,
        spr_bul_rice,
        spr_bul_oval,
        spr_bul_dart,
        spr_bul_needle,
        spr_bul_card,
        spr_bul_star,
        spr_bul_star6,
        spr_bul_crystal,
        spr_bul_rune,
        spr_bul_butterfly,
        spr_bul_flame,
        spr_bul_mote,
    ];
    global.bshape_radius = [
        4.2, 7.0, 15.0, 29.0, 12.5, 26.0, 5.6, 9.0, 7.6, 5.6, 9.0, 10.5, 14.0, 9.0, 10.5, 10.5, 9.5, 5.6,
    ];
    global.bshape_oriented = [
        false, false, false, false, false, false, true, true, true, true, true, false, false, true, false, true, true, false,
    ];
    global.bshape_frames = [
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4,
    ];
    global.bshape_w = [
        38, 48, 68, 108, 60, 90, 48, 62, 60, 76, 60, 56, 68, 58, 54, 70, 80, 42,
    ];
    global.bshape_h = [
        38, 48, 68, 108, 60, 90, 36, 44, 44, 30, 44, 56, 68, 46, 54, 60, 56, 42,
    ];
    global.bshape_spin = [
        0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 2.20, 1.50, 0.00, 0.00, 0.00, 0.00, 2.80,
    ];
}

