/// @desc The spell cut-in's portraits -- GENERATED by tools/make_mika.py. Do
///       not edit: these are measured from the art.
///
/// `cutin_art(_spr)`: where a portrait's eyes are, for the light the cut-in
/// puts on them as they open. Each eye is `[x, y, rx, ry]`: its centre in
/// pixels from the sprite's origin, and its half-width and half-height.
/// `glow` is the colour they shine.

function cutin_art(_spr) {
    if (_spr == spr_cutin_mika) {
        return {
            eyes: [[-165, 33, 74, 59], [165, 65, 82, 53]],
            glow: $FA932B,
        };
    }
    return { eyes: [], glow: c_white };
}
