/// @desc The Hollow Grove's scenery numbers -- GENERATED by
///       tools/make_grove.py. Do not edit.
///
/// Where a charm can be tied: the branch tips are found where the trees are
/// drawn and written out here, as `bullet_table` does for hit radii. Each
/// entry is one tree frame's list of `[u, v]` in the sprite's own box, 0..1
/// from its top-left. A frame may have none.

function grove_table_init() {
    global.grove_hang = [
        [[0.3124, 0.5611]],
        [[0.0963, 0.2334], [0.1345, 0.2252], [0.7551, 0.1153]],
        [[0.0652, 0.1401], [0.0707, 0.4460], [0.0848, 0.2538]],
        [[0.1491, 0.3434], [0.1782, 0.3873], [0.2039, 0.1134]],
        [[0.0622, 0.4514], [0.9051, 0.2536], [0.1099, 0.1252]],
        [[0.1563, 0.1210], [0.2316, 0.4077], [0.7530, 0.4594]],
    ];
}

/// @desc How many places tree frame `_f` offers. Zero is a real answer.
function grove_hang_count(_f) {
    return array_length(global.grove_hang[_f]);
}

/// @desc The `_i`th of them, as `[u, v]`.
function grove_hang_at(_f, _i) {
    return global.grove_hang[_f][_i];
}
