/// @desc The palette -- GENERATED by tools/make_palette.py.
///
/// **Do not edit this file.** GameMaker writes a colour BGR and PIL writes it
/// RGB, so a palette kept in both languages by hand is a palette that is wrong
/// in one of them. `tools/art_common.py` is the source; re-run the generator.


#macro COL_VOID        $140C0A    // behind everything
#macro COL_DUSK        $2C1B18    // the ambient dark of a stage
#macro COL_SLATE       $543E3A    // UI furniture
#macro COL_SILVER      $DCC6BC    // UI lines and small text
#macro COL_PARCHMENT   $D8E4EE
#macro COL_INK         $302428
#macro COL_SZUIX       $BE3E2E    // the player's blue
#macro COL_SZUIX_LIT   $FF826E
#macro COL_ZIGGY       $3036CE    // the first boss's red
#macro COL_ZIGGY_LIT   $5880FF
#macro COL_LIFE        $5842E8    // the health bar, and red shards
#macro COL_MANA        $FFA848    // the special meter, and blue shards
#macro COL_GRAZE       $78D6FF    // near-misses, and gold generally
#macro COL_POWER       $40A8FF
#macro COL_ARCANE      $4A1A24    // the console's ground
#macro COL_ARCANE_LIT  $8E364E
#macro COL_GILT        $4A9AC4    // filigree and rules
#macro COL_GILT_LIT    $96E2FF
#macro COL_RUNE        $FFE06E    // the arcane accent
#macro COL_SIGIL       $FF5496    // Szuix's own magic: the bomb's circle
#macro COL_FLAME       $FFA83C    // Szuix's fire: the body of his shot
#macro COL_STONE       $847676    // the mark ladder: see rank_functions
#macro COL_BRONZE      $3E70B0
#macro COL_AMETHYST    $FF84BA

/// @desc The bullet hues, indexed by BCOL_*. Filled once, from obj_boot.
function palette_init() {
    global.bullet_colour = [
        $4828FF,   // crimson
        $2074FF,   // ember
        $28BAFF,   // amber
        $4AE8FA,   // gold
        $3CF096,   // lime
        $76DC2C,   // jade
        $BEE22C,   // spring
        $FFD638,   // cyan
        $FF8C44,   // azure
        $FF5C74,   // indigo
        $FA54B0,   // violet
        $E048F8,   // magenta
        $B280FF,   // rose
        $FFEEE8,   // bone
    ];

    // The same hues at a third strength, for anything that
    // has to sit *behind* a bullet without competing: the
    // warning line of a laser, a spent shard's afterglow.
    global.bullet_dim = [
        $1B0F61,
        $0C2C61,
        $0F4761,
        $1C585F,
        $175B39,
        $2D5411,
        $485611,
        $615115,
        $61351A,
        $61232C,
        $5F2043,
        $551B5E,
        $443161,
        $615A58,
    ];
}

