/// @desc The Gilded Sanctum's measured numbers -- GENERATED by
///       tools/make_sanctum.py. Do not edit.
///
/// How wide the Bastet is at each height, so `bg_sanctum` can sweep her into
/// a solid. Her outline is read row by row off the shipped sprite's alpha, so
/// the card and the solid agree. Each row is `[v, u0, u1, d]` in the sprite's
/// own box, 0..1 from its top-left: the height, the back and the front of her
/// at that height, and her half-depth. The half-depth is authored (a profile
/// can't say how wide a thing is), as a fraction of the card's width.

function sanctum_table_init() {
    global.bastet_slice = [
        [0.0000, 0.8044, 0.8127, 0.0520],
        [0.0303, 0.7273, 0.8347, 0.0634],
        [0.0606, 0.6997, 0.8540, 0.0749],
        [0.0909, 0.6777, 0.8705, 0.0862],
        [0.1212, 0.6584, 0.9118, 0.0938],
        [0.1515, 0.6198, 0.9449, 0.1014],
        [0.1818, 0.5978, 0.9807, 0.1037],
        [0.2121, 0.5758, 0.9614, 0.0978],
        [0.2424, 0.5537, 0.8981, 0.0918],
        [0.2727, 0.5262, 0.8347, 0.0922],
        [0.3030, 0.4959, 0.8099, 0.1039],
        [0.3333, 0.4545, 0.7989, 0.1157],
        [0.3636, 0.4077, 0.7989, 0.1266],
        [0.3939, 0.3444, 0.8017, 0.1318],
        [0.4242, 0.2700, 0.8017, 0.1370],
        [0.4545, 0.1901, 0.8017, 0.1422],
        [0.4848, 0.1240, 0.8017, 0.1474],
        [0.5152, 0.0799, 0.7989, 0.1525],
        [0.5455, 0.0523, 0.7961, 0.1574],
        [0.5758, 0.0358, 0.7961, 0.1623],
        [0.6061, 0.0248, 0.7934, 0.1672],
        [0.6364, 0.0193, 0.7906, 0.1722],
        [0.6667, 0.0165, 0.7906, 0.1758],
        [0.6970, 0.0165, 0.7906, 0.1748],
        [0.7273, 0.0220, 0.7879, 0.1738],
        [0.7576, 0.0275, 0.7879, 0.1727],
        [0.7879, 0.0386, 0.7879, 0.1717],
        [0.8182, 0.0523, 0.7906, 0.1707],
        [0.8485, 0.0634, 0.7961, 0.1674],
        [0.8788, 0.0689, 0.8375, 0.1582],
        [0.9091, 0.0661, 0.9229, 0.1614],
        [0.9394, 0.0441, 0.9421, 0.2247],
        [0.9697, 0.0441, 0.9449, 0.2264],
        [1.0000, 0.1185, 0.8705, 0.2280],
    ];
}

/// @desc Her cross-section at height `_v`, as `[centre, half-length,
///       half-depth]` in the sprite's own box, interpolated between the
///       measured rows.
function bastet_at(_v) {
    var _t = global.bastet_slice;
    var _n = array_length(_t);
    var _i = 0;
    while (_i < _n - 2 && _t[_i + 1][0] < _v) _i++;
    var _a = _t[_i];
    var _b = _t[_i + 1];
    var _s = clamp((_v - _a[0]) / max(0.000001, _b[0] - _a[0]), 0, 1);
    var _u0 = lerp(_a[1], _b[1], _s);
    var _u1 = lerp(_a[2], _b[2], _s);
    return [(_u0 + _u1) * 0.5, (_u1 - _u0) * 0.5, lerp(_a[3], _b[3], _s)];
}
