#!/usr/bin/env python3
"""Write the palette into GML, so the art and the code cannot disagree.

GameMaker stores a colour literal **BGR** and PIL stores it RGB. There is no
way to derive one from the other at run time, so a palette maintained in both
places is a palette that is wrong in one of them -- and the symptom is quiet:
a meter whose fill does not match its own glass, a particle that is nearly but
not quite the colour of the bullet that threw it. Wordsearch has the two lists
side by side and a comment asking that they be edited together, which is the
best you can do when the art is the only consumer. Here the *game* draws in
these colours too -- every shard, every muzzle flash, every spell wash -- so
the list can simply be generated.

`tools/art_common.py` is the source. This is its output.

Usage:
    python tools/make_palette.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import art_common as A
import gm_new

HEADER = '''/// @desc The palette -- GENERATED by tools/make_palette.py.
///
/// **Do not edit this file.** GameMaker writes a colour BGR and PIL writes it
/// RGB, so a palette kept in both languages by hand is a palette that is wrong
/// in one of them. `tools/art_common.py` is the source; re-run the generator.

'''


def main():
    lines = [HEADER]

    named = [
        ("VOID", A.VOID, "behind everything"),
        ("DUSK", A.DUSK, "the ambient dark of a stage"),
        ("SLATE", A.SLATE, "UI furniture"),
        ("SILVER", A.SILVER, "UI lines and small text"),
        ("PARCHMENT", A.PARCHMENT, ""),
        ("INK", A.INK, ""),
        ("SZUIX", A.SZUIX, "the player's blue"),
        ("SZUIX_LIT", A.SZUIX_LIT, ""),
        ("ZIGGY", A.ZIGGY, "the first boss's red"),
        ("ZIGGY_LIT", A.ZIGGY_LIT, ""),
        ("LIFE", A.LIFE, "the health bar, and red shards"),
        ("MANA", A.MANA, "the special meter, and blue shards"),
        ("GRAZE", A.GRAZE, "near-misses, and gold generally"),
        ("POWER", A.POWER, ""),
        ("ARCANE", A.ARCANE, "the console's ground"),
        ("ARCANE_LIT", A.ARCANE_LIT, ""),
        ("GILT", A.GILT, "filigree and rules"),
        ("GILT_LIT", A.GILT_LIT, ""),
        ("RUNE", A.RUNE, "the arcane accent"),
        ("SIGIL", A.SIGIL, "Szuix's own magic: the bomb's circle"),
        ("FLAME", A.FLAME, "Szuix's fire: the body of his shot"),
        ("STONE", A.STONE, "the mark ladder: see rank_functions"),
        ("BRONZE", A.BRONZE, ""),
        ("AMETHYST", A.AMETHYST, ""),
    ]
    for name, col, note in named:
        tail = ("    // " + note) if note else ""
        lines.append("#macro COL_%-11s %s%s" % (name, A.gm_hex(col), tail))
    lines.append("")

    lines.append("/// @desc The bullet hues, indexed by BCOL_*. Filled once, from obj_boot.")
    lines.append("function palette_init() {")
    lines.append("    global.bullet_colour = [")
    for name, col in A.BULLET_HUES:
        lines.append("        %s,%s// %s" % (A.gm_hex(col),
                                             " " * (10 - len(A.gm_hex(col))),
                                             name))
    lines.append("    ];")
    lines.append("")
    lines.append("    // The same hues at a third strength, for anything that")
    lines.append("    // has to sit *behind* a bullet without competing: the")
    lines.append("    // warning line of a laser, a spent shard's afterglow.")
    lines.append("    global.bullet_dim = [")
    for name, col in A.BULLET_HUES:
        lines.append("        %s," % A.gm_hex(A.mix(col, (0, 0, 0), 0.62)))
    lines.append("    ];")
    lines.append("}")
    lines.append("")

    path = os.path.join(A.ROOT, "scripts", "palette", "palette.gml")
    gm_new.write(path, "\n".join(lines) + "\n")
    print("palette: %d named + %d hues" % (len(named), len(A.BULLET_HUES)))


if __name__ == "__main__":
    main()
